//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageOverlayRenewal.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageOverlayRenewal.Localization.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apply opacity 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_ApplyOpacity {
            get {
                return ResourceManager.GetString("ControlPanel_ApplyOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capacity 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Capacity {
            get {
                return ResourceManager.GetString("ControlPanel_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Custom {
            get {
                return ResourceManager.GetString("ControlPanel_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Image {
            get {
                return ResourceManager.GetString("ControlPanel_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_No {
            get {
                return ResourceManager.GetString("ControlPanel_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No PNG images were detected in the specified directory, the specified directory can be found in Options Panel of this mod. 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_NoPNG {
            get {
                return ResourceManager.GetString("ControlPanel_NoPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Position {
            get {
                return ResourceManager.GetString("ControlPanel_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload texture 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_ReloadTexture {
            get {
                return ResourceManager.GetString("ControlPanel_ReloadTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to default parameters. 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Reset {
            get {
                return ResourceManager.GetString("ControlPanel_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Rotation {
            get {
                return ResourceManager.GetString("ControlPanel_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll the wheel to change, Shift X10, Ctrl X0.1 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_ScrollWheel {
            get {
                return ResourceManager.GetString("ControlPanel_ScrollWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When selected an image, the image pixel information needs to be loaded, and loading time depends on the number of pixels of image. 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_SelectedImageWarning {
            get {
                return ResourceManager.GetString("ControlPanel_SelectedImageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show image 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_ShowImage {
            get {
                return ResourceManager.GetString("ControlPanel_ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Side length 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_SideLength {
            get {
                return ResourceManager.GetString("ControlPanel_SideLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Size {
            get {
                return ResourceManager.GetString("ControlPanel_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string ControlPanel_Yes {
            get {
                return ResourceManager.GetString("ControlPanel_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Settings 的本地化字符串。
        /// </summary>
        internal static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overlay images on top of the map, allowing you to replicate real city. 的本地化字符串。
        /// </summary>
        internal static string MOD_Description {
            get {
                return ResourceManager.GetString("MOD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open PNG directory 的本地化字符串。
        /// </summary>
        internal static string OptionPanel_OpenPNGDirectory {
            get {
                return ResourceManager.GetString("OptionPanel_OpenPNGDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG file path 的本地化字符串。
        /// </summary>
        internal static string OptionPanel_PNGFilePath {
            get {
                return ResourceManager.GetString("OptionPanel_PNGFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Options 的本地化字符串。
        /// </summary>
        internal static string OptionPanel_PNGOptions {
            get {
                return ResourceManager.GetString("OptionPanel_PNGOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show control panel 的本地化字符串。
        /// </summary>
        internal static string OptionPanel_ShowControlPanel {
            get {
                return ResourceManager.GetString("OptionPanel_ShowControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always show reload texture results 的本地化字符串。
        /// </summary>
        internal static string OptionPanel_ShowReloadResults {
            get {
                return ResourceManager.GetString("OptionPanel_ShowReloadResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching PNG files found. 的本地化字符串。
        /// </summary>
        internal static string ReloadMessageBox_NoMatching {
            get {
                return ResourceManager.GetString("ReloadMessageBox_NoMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload {0} texture: 的本地化字符串。
        /// </summary>
        internal static string ReloadMessageBox_Reload0Texture {
            get {
                return ResourceManager.GetString("ReloadMessageBox_Reload0Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add control panel instead of shortcut key. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0ADD1 {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0ADD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Add overlay image parameter settings. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0ADD2 {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0ADD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Added display reload texture results. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0ADD3 {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0ADD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADJ]Because of mod was completely rewritten so settings will be reseted. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0ADJ {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0ADJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed an issue where occasional settings were reseted. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0Fix {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPT]Optimized loading texture logic to improve performance. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0OPT {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Update whole mod framework to improve expansibility. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0UPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0UPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Update show image logic. 的本地化字符串。
        /// </summary>
        internal static string UpdateLog_V1_8_0UPT2 {
            get {
                return ResourceManager.GetString("UpdateLog_V1_8_0UPT2", resourceCulture);
            }
        }
    }
}
