// <auto-generated />
// This file was generated by a T4 template. Do not modify directly.

using CSLModsCommon.Manager;

namespace ImageOverlayRenewal.Localization;

public static class Translations {
    /// <summary>
    /// Transpose
    /// </summary>
    public static string Transpose => LocalizationManager.Localize("Transpose");

    /// <summary>
    /// Flip Vertical
    /// </summary>
    public static string FlipVertical => LocalizationManager.Localize("FlipVertical");

    /// <summary>
    /// Texture Transform Mode
    /// </summary>
    public static string TextureTransformMode => LocalizationManager.Localize("TextureTransformMode");

    /// <summary>
    /// This option affects how PNG images are displayed. FlipVertical is the high-performance mode, while Transpose is the legacy compatibility mode. It can only be changed before entering the game.
    /// </summary>
    public static string TextureTransformModeDescription => LocalizationManager.Localize("TextureTransformModeDescription");

    /// <summary>
    /// Apply
    /// </summary>
    public static string Apply => LocalizationManager.Localize("Apply");

    /// <summary>
    /// Apply opacity
    /// </summary>
    public static string ControlPanel_ApplyOpacity => LocalizationManager.Localize("ControlPanel_ApplyOpacity");

    /// <summary>
    /// Custom
    /// </summary>
    public static string ControlPanel_Custom => LocalizationManager.Localize("ControlPanel_Custom");

    /// <summary>
    /// Image
    /// </summary>
    public static string ControlPanel_Image => LocalizationManager.Localize("ControlPanel_Image");

    /// <summary>
    /// Loop image
    /// </summary>
    public static string ControlPanel_LoopImage => LocalizationManager.Localize("ControlPanel_LoopImage");

    /// <summary>
    /// Opacity
    /// </summary>
    public static string ControlPanel_Opacity => LocalizationManager.Localize("ControlPanel_Opacity");

    /// <summary>
    /// Position
    /// </summary>
    public static string ControlPanel_Position => LocalizationManager.Localize("ControlPanel_Position");

    /// <summary>
    /// Reload texture
    /// </summary>
    public static string ControlPanel_ReloadTexture => LocalizationManager.Localize("ControlPanel_ReloadTexture");

    /// <summary>
    /// Reset to default parameters.
    /// </summary>
    public static string ControlPanel_Reset => LocalizationManager.Localize("ControlPanel_Reset");

    /// <summary>
    /// Rotation
    /// </summary>
    public static string ControlPanel_Rotation => LocalizationManager.Localize("ControlPanel_Rotation");

    /// <summary>
    /// Show image
    /// </summary>
    public static string ControlPanel_ShowImage => LocalizationManager.Localize("ControlPanel_ShowImage");

    /// <summary>
    /// Side length
    /// </summary>
    public static string ControlPanel_SideLength => LocalizationManager.Localize("ControlPanel_SideLength");

    /// <summary>
    /// Size
    /// </summary>
    public static string ControlPanel_Size => LocalizationManager.Localize("ControlPanel_Size");

    /// <summary>
    /// Load Settings
    /// </summary>
    public static string LoadSettings => LocalizationManager.Localize("LoadSettings");

    /// <summary>
    /// Overlay images on top of the map, allowing you to replicate real city.
    /// </summary>
    public static string MOD_Description => LocalizationManager.Localize("MOD_Description");

    /// <summary>
    /// Open PNG directory
    /// </summary>
    public static string OptionPanel_OpenPNGDirectory => LocalizationManager.Localize("OptionPanel_OpenPNGDirectory");

    /// <summary>
    /// PNG file path
    /// </summary>
    public static string OptionPanel_PNGFilePath => LocalizationManager.Localize("OptionPanel_PNGFilePath");

    /// <summary>
    /// PNG Options
    /// </summary>
    public static string OptionPanel_PNGOptions => LocalizationManager.Localize("OptionPanel_PNGOptions");

    /// <summary>
    /// Always show reload texture results
    /// </summary>
    public static string OptionPanel_ShowReloadResults => LocalizationManager.Localize("OptionPanel_ShowReloadResults");

    /// <summary>
    /// Make sure the PNG file is properly placed.
    /// </summary>
    public static string ReloadError => LocalizationManager.Localize("ReloadError");

    /// <summary>
    /// No matching PNG files found.
    /// </summary>
    public static string ReloadMessageBox_NoMatching => LocalizationManager.Localize("ReloadMessageBox_NoMatching");

    /// <summary>
    /// Reload {0} texture:
    /// </summary>
    public static string ReloadMessageBox_Reload0Texture(object arg0) => LocalizationManager.LocalizeFormat("ReloadMessageBox_Reload0Texture", arg0);

    /// <summary>
    /// Are you sure you want to reset to the default parameters?
    /// </summary>
    public static string ResetWarning => LocalizationManager.Localize("ResetWarning");

    /// <summary>
    /// Added Dutch translation.
    /// </summary>
    public static string Changelog_v1_8_4_Translation => LocalizationManager.Localize("Changelog_v1_8_4_Translation");

    /// <summary>
    /// Added Korean translation.
    /// </summary>
    public static string Changelog_v1_8_4_Translation1 => LocalizationManager.Localize("Changelog_v1_8_4_Translation1");

    /// <summary>
    /// Updated to the latest common framework.
    /// </summary>
    public static string Changelog_v1_8_4_Updated => LocalizationManager.Localize("Changelog_v1_8_4_Updated");

    /// <summary>
    /// Fixed an issue where placing PNG files after loading the game would not display images.
    /// </summary>
    public static string Changelog_v1_8_5_Fixed => LocalizationManager.Localize("Changelog_v1_8_5_Fixed");

    /// <summary>
    /// Fixed an issue with incorrect PNG folder directory in the option panel under OSX system.
    /// </summary>
    public static string Changelog_v1_8_5_Fixed1 => LocalizationManager.Localize("Changelog_v1_8_5_Fixed1");

    /// <summary>
    /// Updated to support game version 1.17.1
    /// </summary>
    public static string Changelog_v1_8_5_Updated => LocalizationManager.Localize("Changelog_v1_8_5_Updated");

    /// <summary>
    /// UUI button and separate tool button are now optional.
    /// </summary>
    public static string Changelog_v1_8_5_Updated1 => LocalizationManager.Localize("Changelog_v1_8_5_Updated1");

    /// <summary>
    /// Added independent support for multiple image parameters.
    /// </summary>
    public static string Changelog_v1_9_0_Added => LocalizationManager.Localize("Changelog_v1_9_0_Added");

    /// <summary>
    /// Added support for looping image shortcuts.
    /// </summary>
    public static string Changelog_v1_9_0_Added1 => LocalizationManager.Localize("Changelog_v1_9_0_Added1");

    /// <summary>
    /// Updated mod common.
    /// </summary>
    public static string Changelog_v1_9_1_Updated => LocalizationManager.Localize("Changelog_v1_9_1_Updated");

    /// <summary>
    /// Updated localization.
    /// </summary>
    public static string Changelog_v1_9_1_Translation => LocalizationManager.Localize("Changelog_v1_9_1_Translation");

    /// <summary>
    /// Updated mod common.
    /// </summary>
    public static string Changelog_v1_9_2_Updated => LocalizationManager.Localize("Changelog_v1_9_2_Updated");

    /// <summary>
    /// Code cleanup.
    /// </summary>
    public static string Changelog_v1_9_2_Updated1 => LocalizationManager.Localize("Changelog_v1_9_2_Updated1");

    /// <summary>
    /// Code cleanup.
    /// </summary>
    public static string Changelog_v1_9_3_Updated => LocalizationManager.Localize("Changelog_v1_9_3_Updated");

    /// <summary>
    /// Updated to CSShared framework.
    /// </summary>
    public static string Changelog_v1_9_3_Updated1 => LocalizationManager.Localize("Changelog_v1_9_3_Updated1");

    /// <summary>
    /// Updated localization.
    /// </summary>
    public static string Changelog_v1_9_3_Updated3 => LocalizationManager.Localize("Changelog_v1_9_3_Updated3");

    /// <summary>
    /// Remove Harmony dependency.
    /// </summary>
    public static string Changelog_v1_9_3_Removed => LocalizationManager.Localize("Changelog_v1_9_3_Removed");

    /// <summary>
    /// Fixed serialization exception issues.
    /// </summary>
    public static string Changelog_v1_9_4_Fixed => LocalizationManager.Localize("Changelog_v1_9_4_Fixed");

    /// <summary>
    /// Updated localization.
    /// </summary>
    public static string Changelog_v1_9_4_Translation => LocalizationManager.Localize("Changelog_v1_9_4_Translation");

    /// <summary>
    /// This update automatically resets all settings.
    /// </summary>
    public static string Changelog_v1_10_0_Attention => LocalizationManager.Localize("Changelog_v1_10_0_Attention");

    /// <summary>
    /// Optimized algorithm logic to improve texture processing speed.
    /// </summary>
    public static string Changelog_v1_10_0_Optimized => LocalizationManager.Localize("Changelog_v1_10_0_Optimized");

    /// <summary>
    /// Resolved unpredictable image inversion triggered when switching between images.
    /// </summary>
    public static string Changelog_v1_10_0_Fixed => LocalizationManager.Localize("Changelog_v1_10_0_Fixed");

    /// <summary>
    /// Added PNG image loading mode.
    /// </summary>
    public static string Changelog_v1_10_1_Added => LocalizationManager.Localize("Changelog_v1_10_1_Added");

    /// <summary>
    /// Optimized opacity adjustment UI.
    /// </summary>
    public static string Changelog_v1_10_1_Optimized => LocalizationManager.Localize("Changelog_v1_10_1_Optimized");

    /// <summary>
    /// Fixed the issue where the control panel cannot be invoked in the map editor mode.
    /// </summary>
    public static string Changelog_v1_10_1_Fixed => LocalizationManager.Localize("Changelog_v1_10_1_Fixed");

    /// <summary>
    /// Optimized slow performance when switching between different images.
    /// </summary>
    public static string Changelog_v1_10_2_Optimized => LocalizationManager.Localize("Changelog_v1_10_2_Optimized");

    /// <summary>
    /// Optimized several controls in the control panel.
    /// </summary>
    public static string Changelog_v1_10_2_Optimized1 => LocalizationManager.Localize("Changelog_v1_10_2_Optimized1");

}
